name: 'DABSquared, llc.'
favicon: null
layout_spectrum: 0.17887
typography_spectrum: 0.5993
title: Test
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c1c1c1'
    - '#151515'
    - '#9d9d9d'
    - '#454741'
    - '#7e8283'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
