name: 'DABSquared, llc.'
favicon: null
layout_spectrum: 0.5035751096438617
typography_spectrum: 0.5993
title: Test
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7ebaef'
    - '#121318'
    - '#403e43'
    - '#6c8f46'
    - '#a16b5e'
  brandStrength: 0.2875458241906017
  lightness: 0.4055983033031225
  saturation: 0.49699909635819495
  rhythmicContrast: 0.6847941300366074
purpose: []
