name: 'DABSquared, llc.'
favicon: null
layout_spectrum: 0
typography_spectrum: 0.31463
title: Test
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#134870'
    - '#ffffff'
    - '#7eb655'
    - '#d4dee6'
    - '#5c85a0'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
